### ISSUE TITLE
TOWebViewController not loading data sometime in the first time using in iOS 9.

### ISSUE THREAD

**Issue by lelang** [TimOliver/TOWebViewController#100]
When i use TOWebWiewController, i work great in ios8, but when i check with ios9, TOWebViewController not loading data sometime in the first time using in iOS 9. (like bug happen UIWebView)

**Comment by TimOliver** [comment]
Unless you've got a way to reproduce what is causing that issue, I don't think there's much we can do to resolve it.

If you're still having the problem, please create a new issue and provide reproduction steps there. :)
