### ISSUE TITLE
Xcode warning that umbrella header is missing some header includes

### ISSUE THREAD

**Issue by iosdevben** [TimOliver/TOWebViewController#106]
## Goals

What was the outcome result you wanted to achieve when using this library?

Build without warnings.

## Expected Results

What did you expect to happen?

No warnings in Xcode when I build.

## Actual Results

What actually happened instead?  (Please attach a screenshot/screen recording if possible)

Two warnings are reported by Xcode:
`Umbrella header for module 'TWWebViewController' does not include header 'OnePasswordExtension.h'`
`Umbrella header for module 'TOWebViewController' does not include header 'TOWebViewController+1Password.h'`

## Steps to Reproduce

Build TOWebViewController via Carthage.
Add TOWebViewController to our project.
Try to build our project.
Look at Errors and Warnings log in Xcode.

## Hardware / Software

Xcode 8.2.1, Mac OS 10.12.2, 2015 Retina MacBook Pro.

<img width="416" alt="screen shot 2017-01-03 at 8 13 59 am" src="https://cloud.githubusercontent.com/assets/824608/21596236/a0f721e6-d18c-11e6-87c7-e47d56ddd838.png">

**Comment by TimOliver** [comment]
Thanks for that @iosdevben!

Hmm, I don't really use Carthage a lot, but this would seem to indicate its a build issue with the dynamic framework itself. I'll have to look into it, but I don't know when I'll get time next.
