### ISSUE TITLE
Left Bar Button Item is still missing

### ISSUE THREAD

**Issue by dlipiz** [TimOliver/TOWebViewController#109]
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> ---
>
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describing the bug you've discovered. If it's 
> a UI bug, please attach a screenshot. If it's an animation bug, please provide a video recording 
> of the bug in action.
>
> ---
>
> Please note that since library is done as a side-project outside of work hours, 
> a timely response cannot be guaranteed. ;)
>
> Please remove this line and everything above it before submitting.

## Goals

What was the outcome result you wanted to achieve when using this library?

## Expected Results

What did you expect to happen?

## Actual Results

What actually happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific URL, please provide it here.

## Hardware / Software

On which version of iOS, and what model of device did you experience this bug?

**Comment by dlipiz** [comment]
Hey Tim, I know that this issue seems to be fixed/closed previously, however I still cant seem to get to a solution so I have created a new issue. Upon initially loading the view Im missing my left bar button item. I have tried many different things but I still cant seem to get it to show up. Im running on Xcode 8.2.1. In the code I add the bar button item on lines 43-48. Any other questions please let me know, and thanks for any help you can provide.
![screen shot 2017-01-26 at 12 53 37 pm](https://cloud.githubusercontent.com/assets/17677727/22343679/01a33920-e3c7-11e6-8bb3-2851294394c6.png)

**Comment by TimOliver** [comment]
Hi @dlipiz! Sorry for the delay!

Hmm, is that an instance of the `TOWebViewController` there in your screenshot?

There's an API in the view controller to let you set left hand bar button items and guarantee the system won't mess with them (This is because the system will put the navigation buttons there on iPad sized layouts). The property name is `applicationLeftBarButtonItems`, so you should be able to just set:

`self.applicationLeftBarButtonItems = @[[GCMBaseViewController hamburgerMenuBarButton]];`

I hope that helped! Good luck!

**Comment by TimOliver** [comment]
Hoping that helped! Feel free to reopen if it didn't.
