### ISSUE TITLE
Setting statusbar style

### ISSUE THREAD

**Issue by rajdhakate** [TimOliver/TOWebViewController#116]
`- (UIStatusBarStyle)preferredStatusBarStyle` never called. How can we set statusbar style to lightContent?

**Comment by TimOliver** [comment]
The status bar color is dictated by the `barStyle` property of the `UINavigationBar` of the `UINavigationController` the view controller is added to. If you set the bar style to black, the status bar should turn to its white tint.

If you're not using a `UINavigationController` and are using a custom view for the top, it might be easiest to subclass `TOWebViewController` and then override the method in your subclass.

Hope that helped!
