### ISSUE TITLE
how to customize the webViewController?

### ISSUE THREAD

**Issue by vinayakpal** [TimOliver/TOWebViewController#118]
hi, i need to implement the in app custom browser which probably look like my app. For that i want to customize this webView controller like changing the navigation controller colour, done button to replace with my own placed button, loading tint colour and many more. please help

**Comment by TimOliver** [comment]
Hi @vinayakpal!

In order to display a navigation bar, it's required this library is encapsulated in a `UINavigationController`. You can access the `navigationBar` property from there and customize it however you like. :)

Hope that helped!
