### ISSUE TITLE
The bottom toolbar not hiding after screen dismissing any reason.

### ISSUE THREAD

**Issue by kishore94** [TimOliver/TOWebViewController#121]
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> ---
>
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describing the bug you've discovered. If it's 
> a UI bug, please attach a screenshot. If it's an animation bug, please provide a video recording 
> of the bug in action.
>
> ---
>
> Please note that since library is done as a side-project outside of work hours, 
> a timely response cannot be guaranteed. ;)
>
> Please remove this line and everything above it before submitting.

## Goals
What was the outcome result you wanted to achieve when using this library?

## Expected Results
The screen need to get close all the subview need to destroy.

## Actual Results
Toolbar still exist below after the screen is disappears . Please check the attached screenshot below.

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific URL, please provide it here.

## Hardware / Software

On which version of iOS, and what model of device did you experience this bug?

**Comment by kishore94** [comment]
![simulator screen shot - iphone 8 plus - 2018-02-27 at 12 21 58](https://user-images.githubusercontent.com/21100209/36714621-f0983718-1bb8-11e8-8958-47ffeef5cd32.png)

**Comment by kishore94** [comment]
![simulator screen shot - iphone 8 plus - 2018-02-27 at 12 21 58](https://user-images.githubusercontent.com/21100209/36714665-123d71f8-1bb9-11e8-8200-3419c8a4da08.png)

**Comment by TimOliver** [comment]
Hi @kishore94! Sorry for the late reply!

You might need to manually hide the toolbar yourself when popping back from the web view controller. It's a lot of effort for the web view controller to save the state of the `UINavigationController` before it was pushed, so it's far easier for you to implement it.

In your `viewWillAppear` method, be sure to add `self.toolBarHidden = YES;` and that should fix it. :)

Good luck!
