### ISSUE TITLE
2.2.7 UI Error on iOS 11

### ISSUE THREAD

**Issue by klaus01** [TimOliver/TOWebViewController#125]
## Expected Results

UI display correctly.

## Actual Results

WebView.top displays an error in the ViewController of the non-transparent navigation bar.

## Steps to Reproduce

``` swift
UINavigationBar.appearance().isTranslucent = false

let vc = TOWebViewController(urlString: urlString)!
self.navigationController?.pushViewController(vc, animated: true)
```
<img width="819" alt="wx20180322-203731 2x" src="https://user-images.githubusercontent.com/338228/37771102-89f355a4-2e11-11e8-94d3-f7aff9980b52.png">

## Hardware / Software

TOWebViewController 2.2.7
iOS 11

## Fix

<img width="799" alt="fix" src="https://user-images.githubusercontent.com/338228/37771092-8335be0a-2e11-11e8-93c1-42812fcba371.png">

**Comment by tokenchu** [comment]
its very good

**Comment by TimOliver** [comment]
Thanks for the thorough issue @klaus01! 

I just refactored the code to handle iOS 11 scroll views better. Can you please test it and see if that's fixed it?

Thanks!

**Comment by TimOliver** [comment]
Since I've removed that offending block of code, I think this should be fixed now.

Please open a new issue with a URL I can test if not. :)
