### ISSUE TITLE
bottom toolbar below bottom safe area iPhone X

### ISSUE THREAD

**Issue by sssandyad** [TimOliver/TOWebViewController#127]
## Goals
the library can support iPhone X layout.

## Expected Results
I expected the view to be like this:

![screen shot 2018-04-19 at 10 57 28 am](https://user-images.githubusercontent.com/6153272/38970935-88d6b3b6-43c2-11e8-9e8d-552ae1b9ad55.png)

I can achieved it by using hacky approach and kinda dirty. But still not perfect :(
I hope it can be supported natively by the library.

## Actual Results

bottom toolbar below bottom safe area iPhone X:

![screen shot 2018-04-19 at 11 10 37 am](https://user-images.githubusercontent.com/6153272/38970927-7f6cf6aa-43c2-11e8-9feb-f4779eb57421.png)

## Steps to Reproduce
Always Reproducible

## Hardware / Software
Hardware: iPhone X
Software: iOS 11.x

**Comment by ducbm051291** [comment]
Have u fixed this ?

**Comment by TimOliver** [comment]
Hi @sssandyad! Sorry for the late reply!

Hmm, I just tested it on iOS 11.4 on both the iOS Simulator and my iPhone X and I can't reproduce it. It's the `UIToolbar` of the parent `UINavigationController`, so it should have always been working from the start.

![screenshot](https://user-images.githubusercontent.com/429119/43154157-522ba7e4-8fae-11e8-9407-b1423b71e998.jpg)

Please try the latest copy in the `master` branch, and if it persists, please open a new issue and provide a detailed description on how you're presenting the library.

Thanks!
