### ISSUE TITLE
没人反应移除UIWebview的问题么

### ISSUE THREAD

**Issue by maybeliu** [TimOliver/TOWebViewController#130]
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> ---
>
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describing the bug you've discovered. If it's 
> a UI bug, please attach a screenshot. If it's an animation bug, please provide a video recording 
> of the bug in action.
>
> ---
>
> Please note that since library is done as a side-project outside of work hours, 
> a timely response cannot be guaranteed. ;)
>
> Please remove this line and everything above it before submitting.

## Goals

What was the outcome result you wanted to achieve when using this library?

## Expected Results

What did you expect to happen?

## Actual Results

What actually happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific URL, please provide it here.

## Hardware / Software

On which version of iOS, and what model of device did you experience this bug?

**Comment by TimOliver** [comment]
Hi! As mentioned in the README, this library was engineered around `UIWebView` and its specific behaviours. When I get the free time, I want to make a new version that does the same for `WKWebView`, but that will be a new repo.

This library is here for people who still explicitly require `UIWebView` for their use-cases.

Thanks for the issue!
