### ISSUE TITLE
part of screen is black while initialize and load request

### ISSUE THREAD

**Issue by yanzhiwei147** [TimOliver/TOWebViewController#35]
I found this problem. when i run demo app on iOS simulator,it can load request at first time appear.
Network environment: 100% lost,make sure it waiting until time out.
Result: contentSize of UIWebView not equal CGSizeZero, I swipe to bottom, found bottom part of screen is display black .
thank you.

**Comment by TimOliver** [comment]
Closing this off. There's really nothing we can do about this when it comes to `UIWebView`s. 
Additionally, I'm not thrilled at adding `WKWebView` after I found out that it doesn't share cookies with the other web connection APIs in iOS.
