### ISSUE TITLE
Conflict with any localization in the main app.

### ISSUE THREAD

**Issue by kjanusz** [TimOliver/TOWebViewController#39]
When using TOWebViewController via CocoaPods, the lproj directories are copied to the root of the main bundle. This causes two issues:

1) They conflict with any localization in the main app.
2) The App Store detects these localized bundles and assumes the app is fully localized into all 6 languages TOWebViewController supports (de, en, es, ja, ko, pl, ..). We only support German.

This is a real problem. I think best idea for pods is to use ressource_bundles instead of resources. http://guides.cocoapods.org/syntax/podspec.html#resource_bundles

**Comment by TimOliver** [comment]
Switched over to `bundle_resources`! Hopefully that took care of that! :)
