### ISSUE TITLE
Communications error

### ISSUE THREAD

**Issue by kavichen** [TimOliver/TOWebViewController#42]
When I tap action button, my app crash. It also happens in example app. 

My ios version is 8.1.2, and my xcode version is 6.1.1.

Test my app on iphone 5.

![screenshot 2014-12-16 10 21 56](https://cloud.githubusercontent.com/assets/1509789/5447739/6cc2eb62-850d-11e4-9628-df91bf777704.png)

**Comment by TimOliver** [comment]
Sorry for the late reply!

Haha! Oh wow. I'm glad that you were able to find out that it wasn't my code, but I'm not happy knowing that it's possible to crash iOS that way. ^_^;

Hope you found out what was causing it to crash in the end!

**Comment by kavichen** [comment]
I try to find what caused the crash.

I'll let you know if there is a progression.

Thanks for your reply.
