### ISSUE TITLE
Navigation toolbar not hiding properly

### ISSUE THREAD

**Issue by elorz007** [TimOliver/TOWebViewController#43]
I'm using this (awesome) viewcontroller but I need to hide the toolbar in some cases. Doing something like this will hide the buttons but the toolbar stays there.

	TOWebViewController *controller = [[TOWebViewController alloc] initWithURLString:webpageUrl];
	controller.navigationButtonsHidden = YES;
	[[self navigationController] pushViewController:controller animated:YES];

I dived in the code and saw that the navigationButtonsHidden setter tries to hide the toolbar but it makes it before viewwillappear so when viewwillappear gets called, the toolbar will show again (empty).

Doing it like this (dispathing it in the next update cycle) works but it's not ideal.

	TOWebViewController *controller = [[TOWebViewController alloc] initWithURLString:webpageUrl];
	dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
		controller.navigationButtonsHidden = YES;
	});
	[[self navigationController] pushViewController:controller animated:YES];

**Comment by iotize** [comment]
+1 on this as experiencing the same issue. Perhaps check for whether or not the navigation buttons are hidden in `-viewWillAppear`? Solves the issue for me, but there might be more states I'm not taking into account.

```
    //see if we need to show the toolbar
    if (self.navigationController && !self.navigationButtonsHidden) {
        if (IPAD == NO) { //iPhone
            if (self.beingPresentedModally == NO) { //being pushed onto a pre-existing stack, so
                [self.navigationController setToolbarHidden:NO animated:animated];
                [self.navigationController setNavigationBarHidden:NO animated:animated];
            }
            else { //Being presented modally, so control the
                self.navigationController.toolbarHidden = NO;
            }
        }
        else {
            [self.navigationController setNavigationBarHidden:NO animated:animated];
            [self.navigationController setToolbarHidden:YES animated:animated];
        }
    }
```

**Comment by thedp** [comment]
Please note that the code for `-viewWillAppear` in the Git, and the Pod `2.0.14` is not the same.
The fix for the current issue is present in the Git, but not in the Pod.

**Comment by jxdwinter** [comment]
+1 Cocoapods 2.0.14 have this issue. @iotize +1.

**Comment by TimOliver** [comment]
D'oh. Sorry guys! I'll update the CocoaPods version soon!

**Comment by dkhamsing** [comment]
Ran into the same issue :sweat_smile:

**Comment by TimOliver** [comment]
Alrighty. I've updated the CocoaPods (fricken finally :sweat_smile: ). Hopefully that's fixed this issue.
