### ISSUE TITLE
Status Bar color

### ISSUE THREAD

**Issue by MattiaConfalonieri** [TimOliver/TOWebViewController#50]
If in your app you have a white status bar when call TOWebViewController status bar is not visible.

In my case i put in  TOWebViewController.m  viewDidLoad add 

    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault];

and in doneButtonTapped

    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];

But maybe is better create a system that check the previous status bar colo and reset it when controller is dismissed

**Comment by TimOliver** [comment]
Hrmm....

Yeah, `[UIApplication setStatusBarStyle:]` is usually disabled unless you explicitly set a property in the app's plist.

If you want to override it, inside the `TOWebViewController`, and set `[UIViewController preferredStatusBarStyle]` to return light content appropriately.

Yeah... trying to get that to by dynamic would be cool, but somewhat tricky. ^_^;
