### ISSUE TITLE
Thoughts on allowing NSURLRequest to be modified?

### ISSUE THREAD

**Issue by uzegonemad** [TimOliver/TOWebViewController#53]
I have a scenario where I need to pass a HTTP header with a request. (It's an oauth bearer token)

Normally, I would make a mutable request and then use the built in methods for adding header fields, but TOWebViewController doesn't seem to expose the request in a manner that I can modify.

I'm posting this more for discussion than anything. What are your thoughts on adding methods to enable exposing the request?

**Comment by uzegonemad** [comment]
This is kinda what I was thinking. If you're ok with it, I'll do a PR.

https://github.com/uzegonemad/TOWebViewController/commit/39c26a5c9be719c2cb28612cdb1449ed5e74a828

**Comment by TimOliver** [comment]
Hi Benjamin!

Sorry for the delay! That's a great idea! I'm totally okay with that if you want to do a PR! :)

Thanks for that!

**Comment by uzegonemad** [comment]
Hey Tim,

No problem - I know how difficult it is to find time for ones own projects!

Although already merged, here's the PR in case any one stumbles upon this in the future: https://github.com/TimOliver/TOWebViewController/pull/57
