### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by paragmajum** [TimOliver/TOWebViewController#54]
Does `TOWebViewController`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by TimOliver** [comment]
Hi Parag!

Yeah, it's basically an extension over the system default `UIWebView` UI control, so it just uses the default WebKit implementation. There might be a way to disable SOP, but that's probably out of the scope of this view controller.
