### ISSUE TITLE
Double click on UIWebview causes unexpected popwindow

### ISSUE THREAD

**Issue by hoorayjJX** [TimOliver/TOWebViewController#56]
This problem only happens on iOS 7.1+
url: repast.baiyele.com/cdd
Looking for your reply,thx
![2015-06-09 5 35 14](https://cloud.githubusercontent.com/assets/3012878/8054867/60c046fc-0ece-11e5-8275-8ccd9d8758eb.png)

**Comment by TimOliver** [comment]
Hi there.
Erm... sorry. I don't think there's anything I can do to fix that from the `TOWebViewController` end. Double-tapping to zoom in is a default feature of `UIWebView`, but it looks like the page itself is doing something weird that's causing that problem.

Something that might help is if you go to the website's code, and inside the `<head>` block, add this:

```
<meta name="viewport" id="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
```

That SHOULD disable the zooming of the `UIWebView`. :) 

Good luck!
