### ISSUE TITLE
When I learned your WebView before the call to the getview method in the push, will lead to premature call loadview and viewwillload, self.navigationController at this time of nil, so it will bring a lot of dependencies in navigationController whether the empty allocation failure

### ISSUE THREAD

**Issue by hongdong** [TimOliver/TOWebViewController#60]
When I learned your WebView before the call to the getview method in the push, will lead to premature call loadview and viewwillload, self.navigationController at this time of nil, so it will bring a lot of dependencies in navigationController whether the empty allocation failure

**Comment by TimOliver** [comment]
I haven't seen any incorrect functionality with referencing `self.navigationController` in the `viewDidLoad` method. Can you please provide a demo app or some sample code showing what the problem is?

**Comment by TimOliver** [comment]
I've moved my navigation controller logic to `viewWillAppear` now. Hopefully that'll fix it!
