### ISSUE TITLE
Russian and ukranian localizations are located at wrong path

### ISSUE THREAD

**Issue by kanstantsin** [TimOliver/TOWebViewController#62]
Hi!

Directories for ru.lproj and uk.lproj are located inside of en.lproj directory, so these localizations don't work.
I would also suggest to use ```initWithBarButtonSystemItem:UIBarButtonSystemItemDone``` for Done button. It will use system localization for 'Done' text, so no localization is needed on iOS 6+, while UI looks the same.

**Comment by kanstantsin** [comment]
Here is the fix #63

**Comment by TimOliver** [comment]
PR merged! Thanks a lot for that! :)
