### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by MattiaConfalonieri** [TimOliver/TOWebViewController#69]
Hi, how use your view controller in landscape mode in a only portrait app?

**Comment by TimOliver** [comment]
The view controller supports both landscape and portrait rotations out of the box. If you want to explicitly lock this view controller to landscape, you'll have to change its rotation callback methods (i.e. - `[UIViewController supportedInterfaceOrientations]`, either by modifying it in the code directly, or (more safely), subclassing it.

In terms of good app design, I would recommend making it that your app 'supports' all orientations, but making it so all of your main view controllers only return that they work in portrait mode, and then letting this one work in both. :)

Hope that helped!
