### ISSUE TITLE
Error when using tab bar controller

### ISSUE THREAD

**Issue by qquestel** [TimOliver/TOWebViewController#71]
Hi When i use a standard tab bar the towebviecontrooler loads fine... However if i use a storyboard tabbar controller i get the following error.

Can you assist?

![screen shot 2015-10-02 at 10 09 49 pm](https://cloud.githubusercontent.com/assets/6721893/10261014/afbcf44c-6952-11e5-9ad9-cdf8d3a9dae9.png)

**Comment by TimOliver** [comment]
Hi there! Um.... I'm not too sure, sorry! I don't think I can really provide that sort of support. ^_^;;

Taking a stab in the dark, the only difference in doing it with a storyboard should be the `init` method that gets called. The one from the storyboard doesn't let you specify a URL at that point, so you'd have to manually set the URL for the controller somewhere else, possibly in the storyboard's segue.

Additionally, I've noticed `[self initWithURL:add]` in there. Using that code like that is incorrect, and may be yielding unpredictable results. If you're going to modify the library, setting `self.url = add` should do the trick.

Good luck!
