### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by paulshapiro** [TimOliver/TOWebViewController#76]
Hey there,

Thanks for the lib. Looks great and excited to use it. 
Want to let you know about a minor typo.

    TOWebViewController *webViewController = [[TOWebViewController alloc] initWithURL:[NSURL URLWithString:@"http://www.apple.com/"];

should be

    TOWebViewController *webViewController = [[TOWebViewController alloc] initWithURL:[NSURL URLWithString:@"http://www.apple.com/"]];

**Comment by TimOliver** [comment]
Haha oh! Nicely spotted!

Thanks for that! All fixed now! :)
