### ISSUE TITLE
there is not way to use webViewDidFinishLoad

### ISSUE THREAD

**Issue by mclkyo** [TimOliver/TOWebViewController#77]
i want to add a JSContext to webview in webViewDidFinishLoad function,but there is no way to implementation this method,Can you add a block like shouldStartLoadRequestHandler?thank you

**Comment by TimOliver** [comment]
Thanks for the PR fixing this! I've been meaning to properly expose the `UIWebView` delegate out of this class for a while now. Thanks again for doing that!

**Comment by mclkyo** [comment]
i think expose the UIWebView delegate out will be a good idea
