### ISSUE TITLE
Wrong to add one more TabBar :(

### ISSUE THREAD

**Issue by Nihility-Ming** [TimOliver/TOWebViewController#89]
When I was at the top of the TabBarController, there was TabBar. Then I use the following code:

```Objective-C
TOWebViewController *webViewController = [[TOWebViewController alloc] initWithURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@%@",kHostURLString,@"jr_abouts.html"]]];
webViewController.title = @"产品介绍";
webViewController.hidesBottomBarWhenPushed = YES;
[self.navigationController pushViewController:webViewController animated:YES];
```
Pop hand gesture to return to half, and then I cancel the pop gesture, stay in the TOWebViewController, it occurs Bug.
My TabBarController is wrong to add one more TabBar.

**Comment by TimOliver** [comment]
Hi there @Nihility-Ming! Sorry for the delay!

Oh dear. I'm sorry. I never intended for this library to be pushed to a `UITabBarController` so I'm not sure how well it would work. I sadly don't have time to add custom features like this, but I'll leave this issue open in case anyone else wants to contribute.

In the meantime, can you please post a video of what the issue looks like?

**Comment by TimOliver** [comment]
Closing this since I haven't heard anything for a while. Please re-open if you still need help!
