### ISSUE TITLE
Address Bar

### ISSUE THREAD

**Issue by skram** [TimOliver/TOWebViewController#9]
Add an address bar for free browsing. Great library, Thanks!

**Comment by TimOliver** [comment]
I sadly never got around to adding an address bar to this library, even though I did write one: https://github.com/TimOliver/TOSearchBar

Sadly, now that `UIWebView` is now deprecated in iOS 12, I won't be adding anymore features to this library. Instead, I'll be starting a new one that uses `WKWebView` instead.

Thanks so much for the feature request. :)
