### ISSUE TITLE
TabBar error 

### ISSUE THREAD

**Issue by zfx5130** [TimOliver/TOWebViewController#90]
if the web view add  interactivePopGestureRecognizer , when view back with popGesture again , the property  navigationButtonsHidden  set is the tabbar title is hidden ,but the tabbar is not hidden. how to reslut this . the error image  like this .
[bug gif Image](https://github.com/zfx5130/ToWebViewControllerTestDemo/blob/master/bug.gif)
this is test demo, the bug.gif is the error gif image , you can look it

**Comment by TimOliver** [comment]
Um...

**Comment by zfx5130** [comment]
I resoved..thx. I use you code ,but this is not the lasest branch  if i use the pod install, i must be use 
pod 'TOWebViewController', :git => 'https://github.com/TimOliver/TOWebViewController.git' this way to insall you master branch code to resove,,,

**Comment by TimOliver** [comment]
Oh! Whoops, okay I better put up a new release to CocoaPods! I thought I already had. 

Thanks for that!
