### ISSUE TITLE
ios 7 toolbar

### ISSUE THREAD

**Issue by tomeron11** [TimOliver/TOWebViewController#92]
Hi
in ios7 iphone the bottom toolbar appears at the top. both in modal view and navigation view.
also in your example...

**Comment by TimOliver** [comment]
Hi @tomeron11! Sorry for the delay in replying.

Uh-oh. Can you post a screenshot?

**Comment by tomeron11** [comment]
![screen shot 2016-07-04 at 10 41 26 am](https://cloud.githubusercontent.com/assets/9640244/16553907/2ee43ce4-41d4-11e6-8ab0-6eaed0088743.png)

hi. attached from iPhone 4s, ios7

**Comment by tomeron11** [comment]
it's working great now :-)

**Comment by TimOliver** [comment]
Excellent! Glad that fixed it! :D
