### ISSUE TITLE
this toWebViewController  can support IPV6？

### ISSUE THREAD

**Issue by zfx5130** [TimOliver/TOWebViewController#94]

**Comment by TimOliver** [comment]
It should do! The library pretty much directly passes whichever `NSURL` you specify straight to the `UIWebView` instance in it, so as long as Apple is properly supporting it, I don't see any library-constrained reason why this wouldn't work.

Give it a try, and let me know if you actually do come across any problems!

**Comment by zfx5130** [comment]
Okay, thanks.
