### ISSUE TITLE
Change the properties colors and image of the webview

### ISSUE THREAD

**Issue by amycheong19** [TimOliver/TOWebViewController#96]
Hi,

I would like to change the "< back" and other icon's image and texts colour, is it possible to do so?

**Comment by TimOliver** [comment]
Hi there @amycheong19! Sorry for the delay!

Yeah! You should be able to with the `buttonTintColor` property of the `TOWebViewController` class. Is that what you were looking for?

**Comment by TimOliver** [comment]
I THINK we managed to resolve this in the end. Feel free to re-open if otherwise!
