### ISSUE TITLE
hi,how to load html file?

### ISSUE THREAD

**Issue by yangzheng006** [TimOliver/TOWebViewController#98]
hi
i want to load a html file,how to do that ?

**Comment by TimOliver** [comment]
Hi! Load an HTML file how? Just a local one?

**Comment by yangzheng006** [comment]
yes

**Comment by TimOliver** [comment]
You can't at the moment. That functionality would need to be added.

**Comment by yangzheng006** [comment]
thanks

**Comment by TimOliver** [comment]
No problems!
